version: '3'

volumes:
  db_data:

services:
  nginx:
    image: ahp-rest:lb
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ahp-rest.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  db:
    image: ahp-rest:db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=lewy
      - POSTGRES_PASSWORD=aaa
  ahp-rest:
    image: ahp-rest:app
    volumes:
      - /home/demonizer/projects/rest/ahp-rest/ahp_rest:/root/ahp_rest
    environment:
      - DB_USER=lewy
      - DB_PASSWORD=aaa
      - DB_HOST=db
      - DJANGO_SETTINGS_MODULE=ahp_rest.settings
    command: /bin/bash -f "/root/start.sh"